apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: alyas=base-image
    argocd-image-updater.argoproj.io/write-back-method: git
    # argocd-image-updater.argoproj.io/alyas.update-strategy: name
    # argocd-image-updater.argoproj.io/alyas.allow-tags: null

  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: null
    server: https://kubernetes.default.svc
  project: twygr
  source:
    path: manifest
    repoURL: git@github.com:draiimon/devops-playground.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
