FROM node:18-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Add these two lines to catch the GitHub Secret during build
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=http://fast-api-staging.local:8000

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
