apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: demo
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: testdb
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword
